#!/usr/bin/python3

import os

# Replace this with the location of the gtk src directory on your machine.
# You can get the sources with:
# git clone https://gitlab.gnome.org/GNOME/gtk.git
GTK_SRC_LOCATION = "~/repos/gtk"

XSOCKET_DIR = "/tmp/.X11-unix/"
USER = "dev"

x_sockets = [os.path.join(XSOCKET_DIR, s) for s in os.listdir(XSOCKET_DIR)]
x_socket_flags = []
for s in x_sockets:
  x_socket_flags.append("-v " + s + ":" + s)

os.system("docker build -t gtk .")

cmd = ["docker run",
       "-v " + GTK_SRC_LOCATION + ":/home/" + USER + "/gtk",
       " ".join(x_socket_flags),
       "-e DISPLAY=$DISPLAY -it gtk"]
os.system(" ".join(cmd))
