#!/usr/bin/python3

import os

# Replace this with the location of the gtk src directory on your machine.
# You can get the sources with:
# git clone https://gitlab.gnome.org/GNOME/gtk.git
GTK_SRC_LOCATION = "~/repos/gtk"

os.system("docker build -t gtk .")

os.system("docker run -v " + GTK_SRC_LOCATION + ":/media/gtk -it gtk")
