#!/usr/bin/python3

import os

# Replace this with the location of the gtk src directory on your machine.
# You can get the sources with:
# git clone https://gitlab.gnome.org/GNOME/gtk.git
GTK_SRC_LOCATION = "~/repos/gtk"

XSOCKET = "/tmp/.X11-unix/X0"
USER = "dev"

os.system("docker build -t gtk .")

os.system("docker run " + \
          "-v " + GTK_SRC_LOCATION + ":/home/" + USER + "/gtk " + \
          "-v " + XSOCKET + ":" + XSOCKET + " " + \
          "-e DISPLAY=$DISPLAY -it gtk")
