#!/usr/bin/python3

import getpass
import os

PKG = "docker-ce"

def module_exists(module_name):
    try:
        __import__(module_name)
    except ImportError:
        return False
    else:
        return True

if module_exists("apt"):
  import apt
  cache = apt.Cache()
  if PKG in cache and cache[PKG].is_installed:
    print(PKG + " is already installed, exiting.")
    sys.exit(0)

# Install Docker.
os.system("sudo apt-get update")
os.system("sudo apt-get -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common")
os.system("curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -")
os.system('sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"')
os.system("sudo apt-get update")
os.system("sudo apt-get -y install " + PKG)

# Avoid having to run all Docker commands with sudo.
os.system("sudo usermod -aG docker " + getpass.getuser())

print("Now please log out and log back in before using Docker")

# Log out and back in.
